version: "3.9"

services:
  okloa:
    build:
      context: .
      dockerfile: Dockerfile
    image: okloa/app:latest
    ports:
      - "8501:8501"
    environment:
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
      # ACTIVE_PROJECT: sample_project
      # DEVELOPER_MODE: "false"
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_REGION_NAME: ${S3_REGION_NAME}
      SCW_ACCESS_KEY: ${SCW_ACCESS_KEY}
      SCW_SECRET_KEY: ${SCW_SECRET_KEY}
      JINA_API_KEY: ${JINA_API_KEY}
      JINA_MODEL_URL: ${JINA_MODEL_URL}
      JINA_MODEL_NAME: ${JINA_MODEL_NAME}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      USER: ${USER}
      ACTIVE_PROJECT: ${ACTIVE_PROJECT}
      DEVELOPER_MODE: ${DEVELOPER_MODE}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ./data:/app/data
      # - ./.ragatouille:/app/.ragatouille
      
